name: Jake Nickell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76816
title: "Jake Nickell –\_Coolest Dude on Earth"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d2ce'
    - '#1b100e'
    - '#6c6764'
    - '#fffeff'
    - '#00857e'
  brandStrength: 0.75
  lightness: 0.19305775803513825
  saturation: 0.7716424679383636
  rhythmicContrast: 0.25
purpose: []
